# Generated by Django 4.2.1 on 2023-05-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_creator_alter_task_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_task",
                to="tasks.task",
            ),
        ),
    ]
